server:
  port: 8080
  servlet:
    context-path: /api
  forward-headers-strategy: framework

spring:
  flyway:
    enabled: true
    encoding: UTF-8

  datasource:
    url: ${DB_URL}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    #    url: jdbc:mysql://${DB_HOST}/${DB_DATABASE}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET_ID}
            #            redirect-uri: "{baseUrl}/api/oauth2/login/{registrationId}"
            redirect-uri: https://api.moyeoit.com/api/api/oauth2/login/google
            scope:
              - email
              - profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: Kakao
            authorization-grant-type: authorization_code
            #            redirect-uri: "{baseUrl}/api/oauth2/login/{registrationId}"
            redirect-uri: https://api.moyeoit.com/api/api/oauth2/login/kakao
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: client_secret_post
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expire-time: 1800
  refresh-token-expire-time: 604800

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  newrelic:
    metrics:
      export:
        enabled: true
        api-key: ${NEW_RELIC_API_KEY}
        account-id: ${NEW_RELIC_ACCOUNT_ID}
        uri: https://insights-collector.newrelic.com
        step: 1m

app:
  s3:
    bucket: ${S3_BUCKET_NAME}
    urlBase: ${S3_URL_BASE}